export const CREATE_CHANNEL = "CREATE_CHANNEL";
export const SET_CHANNELS = "SET_CHANNEL";
export const SET_CURRENT_CHANNEL = "SET_CURRENT_CHANNEL";

export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const SET_MESSAGES = "SET_MESSAGES";

export const CREATE_USER = 'CREATE_USER'
export const SET_PROFILE = 'SET_PROFILE'
export const LOGOUT_PROFILE = 'LOGOUT_PROFILE'
